"""003_audit_ledger_and_signatures

Revision ID: 24c271ccd591
Revises: 261c2cec3c72
Create Date: 2026-09-15 21:25:58.021320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24c271ccd591'
down_revision: Union[str, None] = '261c2cec3c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_hash')
    )
    op.create_index(op.f('ix_audit_ledger_action'), 'audit_ledger', ['action'], unique=False)
    op.create_index(op.f('ix_audit_ledger_created_at'), 'audit_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_ledger_entity_id'), 'audit_ledger', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_ledger_organization_id'), 'audit_ledger', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_ledger_user_id'), 'audit_ledger', ['user_id'], unique=False)
    op.create_table('electronic_signatures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('signature_meaning', sa.String(length=64), nullable=False),
    sa.Column('snapshot_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electronic_signatures_entity_id'), 'electronic_signatures', ['entity_id'], unique=False)
    op.create_index(op.f('ix_electronic_signatures_organization_id'), 'electronic_signatures', ['organization_id'], unique=False)
    op.create_index(op.f('ix_electronic_signatures_signature_timestamp'), 'electronic_signatures', ['signature_timestamp'], unique=False)
    op.create_index(op.f('ix_electronic_signatures_user_id'), 'electronic_signatures', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_electronic_signatures_user_id'), table_name='electronic_signatures')
    op.drop_index(op.f('ix_electronic_signatures_signature_timestamp'), table_name='electronic_signatures')
    op.drop_index(op.f('ix_electronic_signatures_organization_id'), table_name='electronic_signatures')
    op.drop_index(op.f('ix_electronic_signatures_entity_id'), table_name='electronic_signatures')
    op.drop_table('electronic_signatures')
    op.drop_index(op.f('ix_audit_ledger_user_id'), table_name='audit_ledger')
    op.drop_index(op.f('ix_audit_ledger_organization_id'), table_name='audit_ledger')
    op.drop_index(op.f('ix_audit_ledger_entity_id'), table_name='audit_ledger')
    op.drop_index(op.f('ix_audit_ledger_created_at'), table_name='audit_ledger')
    op.drop_index(op.f('ix_audit_ledger_action'), table_name='audit_ledger')
    op.drop_table('audit_ledger')
    # ### end Alembic commands ###