"""002_procurement_and_inventory_matrix

Revision ID: 261c2cec3c72
Revises: 69fa23f45c0f
Create Date: 2026-09-13 22:12:40.848413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261c2cec3c72'
down_revision: Union[str, None] = '69fa23f45c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###