"""004_outbox_temperature_compliance

Revision ID: 29bef24bce15
Revises: 24c271ccd591
Create Date: 2026-09-15 22:31:11.358156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29bef24bce15'
down_revision: Union[str, None] = '24c271ccd591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_organization_id'), 'compliance_rules', ['organization_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_organization_id'), 'outbox_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('compliance_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_incidents_created_at'), 'compliance_incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_incidents_organization_id'), 'compliance_incidents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_incidents_reference_id'), 'compliance_incidents', ['reference_id'], unique=False)
    op.create_table('temperature_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_identifier', sa.String(length=128), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('min_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('storage_location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_identifier')
    )
    op.create_index(op.f('ix_temperature_devices_organization_id'), 'temperature_devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_temperature_devices_storage_location_id'), 'temperature_devices', ['storage_location_id'], unique=False)
    op.create_table('temperature_excursions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('observed_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('allowed_minimum', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('allowed_maximum', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('storage_location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_excursions_organization_id'), 'temperature_excursions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_temperature_excursions_started_at'), 'temperature_excursions', ['started_at'], unique=False)
    op.create_index(op.f('ix_temperature_excursions_storage_location_id'), 'temperature_excursions', ['storage_location_id'], unique=False)
    op.create_table('temperature_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('storage_location_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['temperature_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_records_device_id'), 'temperature_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_temperature_records_organization_id'), 'temperature_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_temperature_records_recorded_at'), 'temperature_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_temperature_records_storage_location_id'), 'temperature_records', ['storage_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature_records_storage_location_id'), table_name='temperature_records')
    op.drop_index(op.f('ix_temperature_records_recorded_at'), table_name='temperature_records')
    op.drop_index(op.f('ix_temperature_records_organization_id'), table_name='temperature_records')
    op.drop_index(op.f('ix_temperature_records_device_id'), table_name='temperature_records')
    op.drop_table('temperature_records')
    op.drop_index(op.f('ix_temperature_excursions_storage_location_id'), table_name='temperature_excursions')
    op.drop_index(op.f('ix_temperature_excursions_started_at'), table_name='temperature_excursions')
    op.drop_index(op.f('ix_temperature_excursions_organization_id'), table_name='temperature_excursions')
    op.drop_table('temperature_excursions')
    op.drop_index(op.f('ix_temperature_devices_storage_location_id'), table_name='temperature_devices')
    op.drop_index(op.f('ix_temperature_devices_organization_id'), table_name='temperature_devices')
    op.drop_table('temperature_devices')
    op.drop_index(op.f('ix_compliance_incidents_reference_id'), table_name='compliance_incidents')
    op.drop_index(op.f('ix_compliance_incidents_organization_id'), table_name='compliance_incidents')
    op.drop_index(op.f('ix_compliance_incidents_created_at'), table_name='compliance_incidents')
    op.drop_table('compliance_incidents')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_organization_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_compliance_rules_organization_id'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###