"""002_procurement_and_inventory_matrix

Revision ID: 69fa23f45c0f
Revises: 24208e4a5d48
Create Date: 2026-09-13 22:12:32.956395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fa23f45c0f'
down_revision: Union[str, None] = '24208e4a5d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('compliance_status', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'supplier_code', name='uq_suppliers_org_code')
    )
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_number', sa.String(length=128), nullable=False),
    sa.Column('lot_number', sa.String(length=128), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_quarantined', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('release_status', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'batch_number', name='uq_batches_product_batch_number')
    )
    op.create_index(op.f('ix_batches_batch_number'), 'batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_batches_expiry_date'), 'batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_batches_organization_id'), 'batches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_batches_product_id'), 'batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_batches_supplier_id'), 'batches', ['supplier_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_damaged', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_quarantined', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('storage_location_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_available = (quantity_on_hand - quantity_reserved)', name='chk_inv_balance_equation'),
    sa.CheckConstraint('quantity_available >= 0', name='chk_inv_qty_available_positive'),
    sa.CheckConstraint('quantity_damaged >= 0', name='chk_inv_qty_damaged_positive'),
    sa.CheckConstraint('quantity_on_hand >= 0', name='chk_inv_qty_on_hand_positive'),
    sa.CheckConstraint('quantity_quarantined >= 0', name='chk_inv_qty_quarantined_positive'),
    sa.CheckConstraint('quantity_reserved >= 0', name='chk_inv_qty_reserved_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'batch_id', 'storage_location_id', name='uq_inventory_prod_batch_loc')
    )
    op.create_index(op.f('ix_inventory_batch_id'), 'inventory', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_organization_id'), 'inventory', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_storage_location_id'), 'inventory', ['storage_location_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_organization_id'), 'purchase_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('received_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_organization_id'), 'goods_receipts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_purchase_order_id'), 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_receipt_number'), 'goods_receipts', ['receipt_number'], unique=True)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('storage_location_id', sa.Uuid(), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_inventory_id'), 'stock_movements', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_organization_id'), 'stock_movements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference_id'), 'stock_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_storage_location_id'), 'stock_movements', ['storage_location_id'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('storage_location_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_accepted', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_rejected', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_items_goods_receipt_id'), 'goods_receipt_items', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_product_id'), 'goods_receipt_items', ['product_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('inspector_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_goods_receipt_id'), 'inspections', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_inspections_organization_id'), 'inspections', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspections_organization_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_goods_receipt_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_goods_receipt_items_product_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_goods_receipt_id'), table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index(op.f('ix_stock_movements_storage_location_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reference_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_organization_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_inventory_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_batch_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_goods_receipts_receipt_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_purchase_order_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_organization_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_organization_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_inventory_storage_location_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_organization_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_batch_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_batches_supplier_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_product_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_organization_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_expiry_date'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###